"""empty message

Revision ID: 02a9243cc065
Revises: f45108fc5b33
Create Date: 2020-06-12 23:09:42.545420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a9243cc065'
down_revision = 'f45108fc5b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production', 'released',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('production', 'slug',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('production', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('production', 'slug',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('production', 'released',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
