"""empty message

Revision ID: 21f96e81fba4
Revises: 
Create Date: 2020-06-12 22:55:57.771736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f96e81fba4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('released', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_credit', sa.String(length=30), nullable=True),
    sa.Column('runtime', sa.SmallInteger(), nullable=True),
    sa.Column('tmdb_id', sa.String(length=10), nullable=True),
    sa.Column('imdb_id', sa.String(length=10), nullable=True),
    sa.Column('nbdb_id', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('imdb_id'),
    sa.UniqueConstraint('nbdb_id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('tmdb_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production')
    # ### end Alembic commands ###
