"""empty message

Revision ID: 68bf28b246d6
Revises: 899da0118558
Create Date: 2020-06-13 01:39:27.268501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bf28b246d6'
down_revision = '899da0118558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'imdb_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('person', 'tmdb_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('production', 'imdb_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('production', 'tmdb_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production', 'tmdb_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('production', 'imdb_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('person', 'tmdb_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('person', 'imdb_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
