"""empty message

Revision ID: 772dbd1743c0
Revises: 68bf28b246d6
Create Date: 2020-06-13 01:51:45.246333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772dbd1743c0'
down_revision = '68bf28b246d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('known_for_department', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'known_for_department')
    # ### end Alembic commands ###
