"""empty message

Revision ID: 899da0118558
Revises: b20322ac991c
Create Date: 2020-06-13 01:28:31.736447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899da0118558'
down_revision = 'b20322ac991c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    import models.media
    op.create_table('person',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('bio_credit', sa.String(length=30), nullable=True),
    sa.Column('headshot', models.media.ImageJson(), nullable=True),
    sa.Column('tmdb_id', sa.String(length=10), nullable=False),
    sa.Column('imdb_id', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('imdb_id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('tmdb_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###
