"""empty message

Revision ID: 97d32b2f0147
Revises: 20ad76bb054e
Create Date: 2020-06-13 02:22:05.995187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d32b2f0147'
down_revision = '20ad76bb054e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directors',
    sa.Column('production_pk', sa.Integer(), nullable=True),
    sa.Column('person_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_pk'], ['person.pk'], ),
    sa.ForeignKeyConstraint(['production_pk'], ['production.pk'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('directors')
    # ### end Alembic commands ###
