"""empty message

Revision ID: b20322ac991c
Revises: 39e51e78efa6
Create Date: 2020-06-12 23:58:08.970780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20322ac991c'
down_revision = '39e51e78efa6'
branch_labels = None
depends_on = None


def upgrade():
    import models.production
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production', sa.Column('poster', models.production.Json(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production', 'poster')
    # ### end Alembic commands ###
