"""empty message

Revision ID: ba69a47334cc
Revises: 97d32b2f0147
Create Date: 2020-06-13 02:23:34.913052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba69a47334cc'
down_revision = '97d32b2f0147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directing',
    sa.Column('production_pk', sa.Integer(), nullable=True),
    sa.Column('person_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_pk'], ['person.pk'], ),
    sa.ForeignKeyConstraint(['production_pk'], ['production.pk'], )
    )
    op.drop_table('directors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directors',
    sa.Column('production_pk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_pk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['person_pk'], ['person.pk'], name='directors_person_pk_fkey'),
    sa.ForeignKeyConstraint(['production_pk'], ['production.pk'], name='directors_production_pk_fkey')
    )
    op.drop_table('directing')
    # ### end Alembic commands ###
